In [18]:
# numpy基础：numpy数组
import numpy as np

ary = np.array([1, 2, 3, 4, 5, 6])
print(type(ary))
# numpy数组的特点：重写了很多算法：
print(ary * 3)
print("-" * 20)
print(ary + 10)
print("*" * 20)
print(ary + ary)

<class 'numpy.ndarray'>
[ 3  6  9 12 15 18]
--------------------
[11 12 13 14 15 16]
********************
[ 2  4  6  8 10 12]


In [34]:
# ndarry数组的创建，任何数据类型都可以。

python_list = [1, 2.5, 3]
np_list = np.array(python_list)

print(np_list)
print(type(np_list))
print(type(python_list))

[1.  2.5 3. ]
<class 'numpy.ndarray'>
<class 'list'>


In [37]:
# ndarry数组创建方式2：起始值（0），终止值，步长（1）

the_created_np_list = np.arange(1, 10, 1)
print(the_created_np_list)
the_created_np_list2 = np.arange(2, 20, 2)
print(the_created_np_list2)

[1 2 3 4 5 6 7 8 9]
[ 2  4  6  8 10 12 14 16 18]


In [5]:
# 构建全0或全1的元素：
a = np.zeros(10, float)
print(a)
b = np.ones(5)
print(b)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1.]


In [17]:
# 构建多维度：
arry2 = np.array([[1, 2, 3], [4, 5, 6]])
a5 = np.zeros_like(arry2)
print(a5)
a6 = np.ones_like(arry2)
print(a6)

[[0 0 0]
 [0 0 0]]
[[1 1 1]
 [1 1 1]]


In [22]:
# 输出维度：
print(arry2.shape)
# 输出尺寸：
print(arry2.size)


(2, 3)
6


TypeError: list indices must be integers or slices, not tuple

In [25]:
# 普通的数组不支持用列表来引入数据：
a = [[1, 2], [2, 3], [3, 4]]
b = np.array(a)
# 这个没问题，可以输出：
print(b[0, 0])
# 这个就要报错：
print(a[0, 0])

1


TypeError: list indices must be integers or slices, not tuple

1
